version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "npm install -g aws-cdk@1.57.0"
  build:
    commands:
      - "mvn clean install"
      - "mkdir gen/cloud-assembly"
      - "cdk synth -o $CODEBUILD_SRC_DIR/gen/cloud-assembly -app 'mvn -e -q exec:java'"
      - "echo \"Generated $(cat gen/cloud-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud-assembly"
  base-directory: "gen/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"