version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - "npm install -g aws-cdk@1.57.0"
  build:
    commands:
      - "mvn clean install"
      - "cdk synth"
      - "echo \"Generated $(cat target/cloud-assembly/*.template.json | wc -l) template lines\""
  post_build:
    commands:
      - "echo \"Build completed at $(date)\""
artifacts:
  name: "cloud-assembly"
  base-directory: "target/cloud-assembly"
  discard-paths: no
  files:
    - "**/*"